### ISSUE TITLE
Gemini CLI error: Module did not self-register.

### ISSUE THREAD

**Issue by dbooom** [bem/gemini#123]
Mac OS X 10.10.2
Node v0.12.0
NPM 2.5.1
Gemini 0.9.8

```
gemini gather tests
```

Here what I get in return
```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ruslan/Projects/Kraftsman/Development/app/wp-content/themes/kraftsman/node_modules/gemini/node_modules/png-img/index.js:6:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by SevInf** [comment]
Hi.
Thanks for the report. Node v0.12 is not supported for now (`gemini` uses native module `png-img` which needs to be updated to the latest C++ API). We are going to do it very soon, but for now you can use it with v0.10

**Comment by alexbaumgertner** [comment]
@dbooom I should try to use
http://brewformulas.org/n or 
http://brewformulas.org/Nvm
for custom nodejs version usage.

**Comment by dbooom** [comment]
Thanks guys.
Should we close this issue for now or wait for Node v0.12 support?

**Comment by SevInf** [comment]
I prefer keeping it open until v0.12 support arrives

**Comment by VanidaT** [comment]
Hi! Would you happen to have a date or a time period of when we can expect node v0.12 to be supported?

**Comment by SevInf** [comment]
Hi.We are planning to start working on it this week and publish the version next week

**Comment by VanidaT** [comment]
Perfect. Thank you!
