### ISSUE TITLE
As for 0.9.x, gemini does not work on Windows anymore.

### ISSUE THREAD

**Issue by SevInf** [bem/gemini#89]
`png-img` does not have a binary module for windows.

**Comment by kostyatam** [comment]
When I tried to take reference shots and got this error:
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: The specified procedure could not be found.

C:\Users\Kostin_K\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\compiled\win32\x64\png_img.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Kostin_K\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\index.js:6:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

Is it the same issue?

**Comment by SevInf** [comment]
@kostyatam no, it should work on Windows now. Are you using node 0.12 or iojs? They are both not supported now, but it will change very soon.
